alias ..='cd ..'
alias ...='cd ../..'

alias dirs='dirs -v'
alias e='exit'
alias jq='jq -C'
alias less='less -R'
alias ll='ls -al'
alias psg='ps fauxwww | grep -v grep | grep'
alias vi=$( which vim )
alias watch='watch -c '

# Enable vi-mode for command line interface
set -o vi

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find/var/log/apache
shopt -s cdspell

# colored grep
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;33'

