alias g='git'
alias ga='git add'
alias gacc='git_all_commit_count'
alias gafc='git_all_file_count'
alias gaf='git_add_files'
alias gag='git aliases | grep'
alias gaia='echo -e "a\n*\nq\n" | git add -i'
alias gall='git add .'
alias gau='git add -u'
alias gb='git branch'
alias gba='git branch -a'
alias gbcc='git_branch_commit_count'
alias gblt='for k in `git branch | perl -pe "s/^..(.*?)( ->.*)?$/\1/"`; do echo -e `git show --pretty=format:"%Cgreen%ci %Cred%cr%Creset" $k -- | head -n 1`\\t$k; done | sort -r'
alias gblth='gblt | head'
alias gbr='git branch -r'
alias gbrlt='for k in `git branch -r | perl -pe "s/^..(.*?)( ->.*)?$/\1/"`; do echo -e `git show --pretty=format:"%Cgreen%ci %Cred%cr%Creset" $k -- | head -n 1`\\t$k; done | sort -r'
alias gbrlth='gbrlt | head'
alias gbrv='git branch -rv'
alias gbvv='git branch -vv'
alias gcadf='git_checkout_all_deleted_files'
alias gcl='git clone'
alias gco='git_checkout_branch'
alias gcob='git checkout -b'
alias gcoc='git_checkout_custom_branch'
alias gcomr='git_checkout_most_recent_branch'
alias gcomrr='git_checkout_most_recent_remote_branch'
alias gcor='git_checkout_remote_branch'
alias gcp='git cherry-pick'
alias gdv='git diff -w "$@" | vim -R -'
alias gg='git grep -n'
alias ggrs='git grep -n --recurse-submodules'
alias gga='f(){ git grep -n --recurse-submodules "alias $1"; unset -f f; }; f'
alias ggl='git grep -l'
alias gglrs='git grep -l --recurse-submodules'
alias glg='git log --grep'
alias gln='git log -n'
alias glns='git log --name-status'
alias glo='git log --graph --pretty=oneline --abbrev-commit'
alias gmom='git merge --no-ff origin/master'
alias gp='git push'
alias gpdo='git push --delete origin'
alias gpforce='git push --force'
alias gpo='git push origin'
alias gpsu='git_push_set_upstream'
alias gqf='git_quick_fix'
alias gradf='git_remove_all_deleted_files'
alias graf='git_restore_all_files'
alias grc='git rebase --continue'
alias grf='git_restore_file'
alias gri='git_rebase_helper'
alias grom='git pull --rebase && git rebase origin/master'
alias grpo='git remote prune origin'
alias grt='cd $(git_root)'
alias grub='git_remove_untracked_branches'
alias gruf='git_remove_untracked_files'
alias gsa='git_stashapply'
alias gsd='git_stashdrop'
alias gsfp='git_stash_force_push'
alias gsl='git stash list'
alias gsp='git stash pop'
alias gspm='git stash push -m'
alias gspmw='git stash push -m "WIP it real good"'
alias gsq='git_squash_commits'
alias gss='git_stashow'
alias gssp='git_stashowp'
alias gst='git status --ignore-submodules'
alias gsu='git submodule update'
alias gsua='git_submodule_update_all'
alias gup='git pull --rebase --autostash'

alias og='open_git_base_url'
alias ogb='open_git_branch_url'

# Long alias names
alias git_all_commit_count='git rev-list --all --count'
alias git_all_file_count='git ls-tree --name-only -r origin/master | wc -l'
alias git_base_url='f(){ local url=https://$(cat .git/config | grep "url = git" | cut -d@ -f2 | sed "s/:/\//" | head -n1); echo ${url%.git}; unset -f f; }; f'
alias git_branch_commit_count='git rev-list --count HEAD ^master'
alias git_checkout_all_deleted_files="git status | grep deleted | awk '{print \$2}' | xargs git checkout --"
alias git_quick_fix='gst && gau && git cm "fix" && gri 2'
alias git_remove_all_deleted_files=$'git status | grep deleted | awk \'{print $2}\' | xargs git rm'
alias git_remove_all_untracked_files='git clean -fdx'
alias git_remove_untracked_branches=$'git checkout -q master && git fetch -q --prune && git branch -vv | awk \'/: gone]/{print $1}\' | xargs -r git branch -d'
alias git_remove_untracked_files=$'f(){ git status | grep "${1:-src}" | awk \'{print $1}\' | xargs rm -rf; unset -f f; }; f'
alias git_remove_untracked_unmerged_branches=$'git checkout -q master && git fetch -q --prune && git branch -vv | awk \'/: gone]/{print $1}\' | xargs -r git branch -D'
alias git_restore_all_files=$'git status | grep "new file" | awk \'{print $3}\' | xargs git restore --staged'
alias git_restore_file=$'f(){ git status | grep "new file" | grep -i "${1:-src}" | awk \'{print $3}\' | xargs git restore --staged; unset -f f; }; f'
alias git_root='if [[ $(git rev-parse --show-cdup) ]]; then git rev-parse --show-cdup; else echo "./"; fi'
alias git_stash_force_push='git stash show -p | git apply && git stash drop'
alias git_submodule_update_all='git submodule update --remote --merge'
alias git_user_commit_count='git shortlog -sn'

# Open url to git related link
alias open_git_base_url='xdg-open $(git_base_url) >/dev/null 2>&1'
alias open_git_branch_url='xdg-open $(git_base_url)/tree/$(git symbolic-ref --short HEAD) >/dev/null 2>&1'

case $OSTYPE in
  linux*)
    alias gd='git diff | vim -R -'
    ;;
  darwin*)
    alias gd='git diff | mate'
    ;;
  darwin*)
    alias gd='git diff'
    ;;
esac

