alias g='git'
alias ga='git add'
alias gaf='git_add_files'
alias gag='git aliases | grep'
alias gaia='echo -e "a\n*\nq\n" | git add -i'
alias gall='git add .'
alias gau='git add -u'
alias gb='git branch'
alias gba='git branch -a'
alias gblt='for k in `git branch | perl -pe "s/^..(.*?)( ->.*)?$/\1/"`; do echo -e `git show --pretty=format:"%Cgreen%ci %Cred%cr%Creset" $k -- | head -n 1`\\t$k; done | sort -r'
alias gblth='gblt | head'
alias gbr='git branch -r'
alias gbrlt='for k in `git branch -r | perl -pe "s/^..(.*?)( ->.*)?$/\1/"`; do echo -e `git show --pretty=format:"%Cgreen%ci %Cred%cr%Creset" $k -- | head -n 1`\\t$k; done | sort -r'
alias gbrlth='gbrlt | head'
alias gbrv='git branch -rv'
alias gbvv='git branch -vv'
alias gcadf='git_checkout_all_deleted_files'
alias gcl='git clone'
alias gco='git_checkout_branch'
alias gcob='git checkout -b'
alias gcoc='git_checkout_custom_branch'
alias gcomr='git_checkout_most_recent_branch'
alias gcomrr='git_checkout_most_recent_remote_branch'
alias gcor='git_checkout_remote_branch'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gdv='git diff -w "$@" | vim -R -'
alias gg='git grep -n --recurse-submodules'
alias ggl='git grep -l --recurse-submodules'
alias glg='git log --grep'
alias gln='git log -n'
alias glns='git log --name-status'
alias glo='git log --graph --pretty=oneline --abbrev-commit'
alias gmom='git merge --no-ff origin/master'
alias gp='git push'
alias gpdo='git push --delete origin'
alias gpforce='git push --force'
alias gpo='git push origin'
alias gpsu='git_push_set_upstream'
alias gqf='git_quick_fix'
alias gri='git_rebase_helper'
alias gradf='git_remove_all_deleted_files'
alias grom='git pull --rebase && git rebase origin/master'
alias grpo='git remote prune origin'
alias grt='git_root'
alias grub='git_remove_untracked_branches'
alias gruf='git_remove_untracked_files'
alias gsa='git_stashapply'
alias gsd='git_stashdrop'
alias gsfp='git_stash_force_push'
alias gsl='git stash list'
alias gsp='git stash pop'
alias gspm='git stash push -m'
alias gspmw='git stash push -m "WIP it real good"'
alias gss='git_stashow'
alias gssp='git_stashowp'
alias gst='git status --ignore-submodules'
alias gsu='git submodule update'
alias gsua='git_submodule_update_all'
alias gup='git pull --rebase'

# Long alias names
alias git_checkout_all_deleted_files="git status | grep deleted | awk '{print \$2}' | xargs git checkout --"
alias git_quick_fix='gst && gau && git cm "fix" && gri 2'
alias git_remove_all_deleted_files=$'git status | grep deleted | awk \'{print $2}\' | xargs git rm'
alias git_remove_untracked_branches=$'git checkout -q master && git fetch -q --prune && git branch -vv | awk \'/: gone]/{print $1}\' | xargs -r git branch -d'
alias git_remove_untracked_files=$'f(){ git status | grep -v ":" | grep "${1:-src}" | awk \'{print $1}\' | xargs rm -rf; unset -f f; }; f'
alias git_root='cd $(git rev-parse --show-cdup)'
alias git_stash_force_push='git stash show -p | git apply && git stash drop'
alias git_submodule_update_all='git submodule update --remote --merge'

case $OSTYPE in
  linux*)
    alias gd='git diff | vim -R -'
    ;;
  darwin*)
    alias gd='git diff | mate'
    ;;
  darwin*)
    alias gd='git diff'
    ;;
esac

