alias cg='confgen'
alias cgd='confgen --dev'
alias dbeaver='nohup sh -c ~/dbeaver/dbeaver > /dev/null 2>&1 &'
alias first_sha='git log -n 1; git log -n 1 --format=%H | tr -d "\n" | tmux loadb -'
alias fk_prod='psql -h fortknoxpool.marchex.com -d warehouse_ro'
alias fk_qa='psql -h fortknoxpool.qa.marchex.com -d warehouse -U dev'
alias java6='export JAVA_HOME=/site/jdk/jdk1.6.0_37'
alias java7='export JAVA_HOME=/site/jdk/jdk1.7.0_17'
alias java8='export JAVA_HOME=/site/jdk/jdk1.8.0_60'
alias sp='ssh pulleybuild'
