#!/bin/bash

default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | rev | cut -d/ -f1 | rev)
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $default_branch = $current_branch ]; then
    read -p "You're about to push to '$default_branch'. Are you sure? > " -n 2 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # carry on
    fi
    exit 1 # exit and go read a book
else
    exit 0
fi

