alias acl='aws configure list'
alias aclp='aws configure list-profiles'
alias asgci='aws sts get-caller-identity'
alias assmib='aws_ssm -c emr-di-index-builders'
alias assmib17='aws_ssm -c emr-di-ibs-java-17-g-scaling'
alias assmibw='aws_ssm -p ibw-prod-admin -c emr-ibw'
alias assmibr='aws_ssm -c emr-di-index-builders -r'
alias assmib17r='aws_ssm -c emr-di-ibs-java-17-g-scaling -r'
alias assmibwr='aws_ssm -p ibw-prod-admin -c emr-ibw -r'
alias caco='cat ~/.aws/config'
alias cacr='cat ~/.aws/credentials'
alias cacrg='f(){ cat ~/.aws/credentials | grep -A 4 $1 | save_to_all_clipboards; unset -f f; }; f'
alias vaco='vi ~/.aws/config'
alias vacr='vi ~/.aws/credentials'

