alias acl='aws configure list'
alias aclp='aws configure list-profiles'
alias asdp='aws_set_default_profile'
alias asgci='aws sts get-caller-identity'
alias assm='aws_ssm'
alias assmadev='aws_ssm -c emr-adev-test'
alias assmadevr='aws_ssm -c emr-adev-test -r'
alias assmibs='aws_ssm -c emr-di-ibs'
alias assmibsr='aws_ssm -c emr-di-ibs -r'
alias assmibw='aws_ssm -p ibw-prod-admin -c emr-ibw'
alias assmibwr='aws_ssm -p ibw-prod-admin -c emr-ibw -r'
alias caco='cat ~/.aws/config'
alias cacr='cat ~/.aws/credentials'
alias cacrg='f(){ cat ~/.aws/credentials | grep -A 4 $1 | save_to_all_clipboards; unset -f f; }; f'
alias vaco='vi ~/.aws/config'
alias vacr='vi ~/.aws/credentials'

# Long alias names
alias aws_set_default_profile='f(){ aws configure set default.profile $1; unset -f f; }; f'

