#!/bin/bash

clean_up_test_data() {
  local proctor_test_filename=$1
  rm $proctor_test_filename
}

raw_proctor_test="$1"
proctor_test=$(echo $1 | tr "[:upper:]" "[:lower:]")

case $2 in
     qa)
          ENV="qa"
          ;;
     prod|production)
          ENV="production"
          ;;
     *)
          ENV="qa"
          ;;
esac

[[ $ENV = "qa" ]] && url_env="qa." || url_env=""
pipet_url=https://pipet.sandbox.${url_env}indeed.net/proctor/matrix/definition/$proctor_test

retry_count=0
$(wget -q $pipet_url)
while [ ! -f "$proctor_test" ]; do
  retry_count=$[retry_count + 1]
  echo "INFO: Attempting again in 30 seconds. Retry attempt $retry_count"
  sleep 30

  if [ $retry_count -ge 10 ]; then
    echo "ERROR: proctor test '$proctor_test' does NOT exist after $retry_count retries"
    exit 1
  fi

  $(wget -q $pipet_url)
done

echo "INFO: Found '$proctor_test' in pipet!"

echo "(/) Verified pipet $ENV for proctor test '$proctor_test'"
echo "{code:title=$pipet_url}"
cat $proctor_test | jq .
echo "{code}"

clean_up_test_data $proctor_test
