alias ktcbc='kube_trino_coordinator_bash_command'
alias ktccbs='kube_trino_coordinator_container_bash_shell'
alias ktcbs='kube_trino_coordinator_bash_shell'
alias ktccl='kube_trino_coordinator_container_logs'
alias ktcd='kube_trino_coordinator_describe'
alias ktcgp='kube_trino_coordinator_get_pod'
alias ktcl='kube_trino_coordinator_logs'
alias ktcr='kube_trino_coordinator_restart'
alias ktgp='kube_trino_get_pods'
alias ktlc='kube_trino_list_containers'

# Aliases for trino--dev
alias ktdcbc='kube_trino_coordinator_bash_command dev'
alias ktdccbs='kube_trino_coordinator_container_bash_shell dev'
alias ktdcbs='kube_trino_coordinator_bash_shell dev'
alias ktdccl='kube_trino_coordinator_container_logs dev'
alias ktdcd='kube_trino_coordinator_describe dev'
alias ktdcgp='kube_trino_coordinator_get_pod dev'
alias ktdcl='kube_trino_coordinator_logs dev'
alias ktdcr='kube_trino_coordinator_restart dev'
alias ktdgp='kube_trino_get_pods dev'
alias ktdlc='kube_trino_list_containers dev'

# Aliases for trino--dev2
alias ktd2cbc='kube_trino_coordinator_bash_command dev2'
alias ktd2ccbs='kube_trino_coordinator_container_bash_shell dev2'
alias ktd2cbs='kube_trino_coordinator_bash_shell dev2'
alias ktd2ccl='kube_trino_coordinator_container_logs dev2'
alias ktd2cd='kube_trino_coordinator_describe dev2'
alias ktd2cgp='kube_trino_coordinator_get_pod dev2'
alias ktd2cl='kube_trino_coordinator_logs dev2'
alias ktd2cr='kube_trino_coordinator_restart dev2'
alias ktd2gp='kube_trino_get_pods dev2'
alias ktd2lc='kube_trino_list_containers dev2'

# Aliases for trino--stage
alias ktscbc='kube_trino_coordinator_bash_command stage'
alias ktsccbs='kube_trino_coordinator_container_bash_shell stage'
alias ktscbs='kube_trino_coordinator_bash_shell stage'
alias ktsccl='kube_trino_coordinator_container_logs stage'
alias ktscd='kube_trino_coordinator_describe stage'
alias ktscgp='kube_trino_coordinator_get_pod stage'
alias ktscl='kube_trino_coordinator_logs stage'
alias ktscr='kube_trino_coordinator_restart stage'
alias ktsgp='kube_trino_get_pods stage'
alias ktslc='kube_trino_list_containers stage'

# Aliases for trino--interactive
alias kticbc='kube_trino_coordinator_bash_command interactive'
alias kticcbs='kube_trino_coordinator_container_bash_shell interactive'
alias kticbs='kube_trino_coordinator_bash_shell interactive'
alias kticcl='kube_trino_coordinator_container_logs interactive'
alias kticd='kube_trino_coordinator_describe interactive'
alias kticgp='kube_trino_coordinator_get_pod interactive'
alias kticl='kube_trino_coordinator_logs interactive'
alias kticr='kube_trino_coordinator_restart interactive'
alias ktigp='kube_trino_get_pods interactive'
alias ktilc='kube_trino_list_containers interactive'

# Aliases for trino--prod
alias ktpcbc='kube_trino_coordinator_bash_command prod'
alias ktpccbs='kube_trino_coordinator_container_bash_shell prod'
alias ktpcbs='kube_trino_coordinator_bash_shell prod'
alias ktpccl='kube_trino_coordinator_container_logs prod'
alias ktpcd='kube_trino_coordinator_describe prod'
alias ktpcgp='kube_trino_coordinator_get_pod prod'
alias ktpcl='kube_trino_coordinator_logs prod'
alias ktpcr='kube_trino_coordinator_restart prod'
alias ktpgp='kube_trino_get_pods prod'
alias ktplc='kube_trino_list_containers prod'


# Long alias names
alias kube_trino_coordinator_bash_command=$'f(){ kubectl exec -n "trino--$1" $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\') -c indeed-trino-coordinator -- bash -c "$2"; unset -f f; }; f'
alias kube_trino_coordinator_bash_shell=$'f(){ kubectl exec -it -n "trino--$1" $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\') -c indeed-trino-coordinator -- /bin/bash; unset -f f; }; f'
alias kube_trino_coordinator_container_bash_shell=$'f(){ kubectl exec -it -n "trino--$1" $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\') -c indeed-trino-coordinator -c "$2" -- /bin/bash; unset -f f; }; f'
alias kube_trino_coordinator_container_logs=$'f(){ kubectl -n "trino--$1" logs -f $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\') -c "$2"; unset -f f; }; f'
alias kube_trino_coordinator_describe=$'f(){ kubectl -n "trino--$1" describe pod $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\'); unset -f f; }; f'
alias kube_trino_coordinator_get_pod=$'f(){ kubectl -n "trino--$1" get pod $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\') -o yaml; unset -f f; }; f'
alias kube_trino_coordinator_logs=$'f(){ kubectl -n "trino--$1" logs -f $(kubectl -n "trino--$1" get pods | grep coordinator | awk \'{print $1}\') -c indeed-trino-coordinator; unset -f f; }; f'
alias kube_trino_coordinator_restart=$'f(){ kubectl -n "trino--$1" rollout restart deployment "trino-aws$1-coordinator"; unset -f f; }; f'
alias kube_trino_get_pods='f(){ kubectl -n "trino--$1" get pods; unset -f f; }; f'
alias kube_trino_list_containers=$'f(){ kubectl -n "trino--$1" get pods -o jsonpath='{.items[*].spec.containers[*].name}'; unset -f f; }; f'

