alias ach='ant clean hobo'
alias achd='ant clean hobo-deploy'
alias achda='ant clean hobo-deploy-all'
alias act='ant clean test'
alias ah='ant hobo'
alias ahd='ant hobo-deploy'
alias ahda='ant hobo-deploy-all'
