alias c='cheat'
alias ce='cheat -e'
alias ceu='cheat -e useful'
alias cl='f(){ cheat $1 | less; unset -f f; }; f'
alias cs='f(){ cheat -s $1; unset -f f; }; f'
alias csl='f(){ cheat -s $1 | less; unset -f f; }; f'
alias csx='cheat_search_execute'
alias cu='cheat useful'
alias cug='cheat useful | grep'
alias cul='cheat useful | less'
alias cutl='cheat useful | tail'
alias cx='cheat_execute'
alias cxu='cheat_execute_useful'

