alias c='cheat'
alias ce='cheat -e'
alias ceu='cheat -e useful'
alias cl='f(){ cheat $1 | less; unset -f f; }; f'
alias cs='f(){ cheat -s $1; unset -f f; }; f'
alias csl='f(){ cheat -s $1 | less; unset -f f; }; f'
alias ch='cheat_helper'
alias chs='cheat_helper -s'
alias chx='cheat_helper -x'
alias chsx='cheat_helper -s -x'
alias cu='cheat useful'
alias cug='cheat useful | grep'
alias cul='cheat useful | less'
alias cutl='cheat useful | tail'
alias cxu='cheat_helper -a -x useful'

