#!/usr/bin/env bash

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# if not running interactively, don't do anything
[ -z "$PS1" ] && return

# shortcut to dotfiles
export DOTFILES="${HOME}/dotfiles"

source "${DOTFILES}/bash/colors.theme"
source "${DOTFILES}/bash/base.theme"

# source our functions (must go before configs because conditionally_prefix_path is required for some configs)
for config_file in $(find ${DOTFILES} -type f -name *.func); do
  source $config_file
done

# source our configurations
for config_file in $(find ${DOTFILES} -type f -name config.bash); do
  source $config_file
done

# source our aliases
for config_file in $(find ${DOTFILES} -type f -name aliases.bash); do
  source $config_file
done

unset config_file

if [ -a ~/.localrc ]; then source ~/.localrc; fi

if [[ $PROMPT ]]; then
    export PS1=$PROMPT
fi

# Mostly works (sometimes expires, not sure why)
# Also must remain in bashrc otherwise I'm prompted way too often
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  eval `ssh-agent`
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l > /dev/null || ssh-add

