alias ahdhlf='ant hobo-deploy && hobo logs -f $(get_repo_name)'
alias dll='download_log4j_logs'
alias gcli='f(){ git clone git@code.corp.indeed.com:$(get_dir_name)/$1.git; cd $1; unset -f f; }; f'
alias gcliacp='f(){ git clone git@code.corp.indeed.com:$(get_dir_name)/$1.git; cd $1; ant clippy-project; unset -f f; }; f'
alias gcobi='f(){ git checkout -b jira/$(whoami)/$1; unset -f f; }; f'
alias glogj='glogf --json'
alias jira='f(){ DISPLAY=:0 firefox -new-tab -url $JIRA_BASE_URL/browse/${1:-$(git symbolic-ref --short HEAD | grep -o "[^/]*$")}; unset -f f; }; f'
alias jproj='f(){ DISPLAY=:0 firefox -new-tab -url $JIRA_BASE_URL/projects/$(grep jira repo.cfg | cut -d= -f2)/issues; unset -f f; }; f'
alias og='DISPLAY=:0 firefox -new-tab -url $GITLAB_BASE_URL/$(get_repo_product_group_and_name)'
alias ogb='DISPLAY=:0 firefox -new-tab -url $GITLAB_BASE_URL/$(get_repo_product_group_and_name)/tree/$(git symbolic-ref --short HEAD)'
alias ogf='f(){ DISPLAY=:0 firefox -new-tab -url $GITLAB_BASE_URL/$(get_repo_product_group_and_name)/blob/master/$(git ls-tree -r master --name-only | fgrep "$1" | fgrep -iv test)#L$2; unset -f f; }; f'
alias ogft='f(){ DISPLAY=:0 firefox -new-tab -url $GITLAB_BASE_URL/$(get_repo_product_group_and_name)/blob/master/$(git ls-tree -r master --name-only | fgrep "$1" | fgrep -i test)#L$2; unset -f f; }; f'
alias ogmr='DISPLAY=:0 firefox -new-tab -url $GITLAB_BASE_URL/$(get_repo_product_group_and_name)/merge_requests'
alias ognmr='DISPLAY=:0 firefox -new-tab -url "$GITLAB_BASE_URL/$(get_repo_product_group_and_name)/merge_requests/new?utf8=%E2%9C%93&merge_request[source_branch]=$(git symbolic-ref --short HEAD)&merge_request[target_branch]=master&merge_request[title]=$(basename $(git symbolic-ref --short HEAD)): DESCRIPTION"'
alias oll=$'f(){ DISPLAY=:0 firefox -new-tab -url "https://lola.sandbox.indeed.net/?a=$(git grep setAppClass | cut -d "(" -f2 | cut -d "." -f1)&env=${1:-prod}&f=0&hl=1&lvls=WARN%2CERROR&s=$(($(date --date \'-1 hour\' +%s%N)/1000000))&supervisorlogs=0&tzOffset=0"; unset -f f; }; f'
alias olv=$'f(){ DISPLAY=:0 firefox -new-tab -url "https://squall.indeed.com/logviewer?type=$1&source=prod&checked=detailedUID&date=$(($(date --date \'-1 hour\' +%s%N)/1000000))&numRequested=10"; unset -f f; }; f'
alias osg='f(){ DISPLAY=:0 firefox -new-tab -url "https://sourcegraph.corp.indeed.com/search?q=+$1"; unset -f f; }; f'
alias pipet='f(){ DISPLAY=:0 firefox -new-tab -url https://pipet.sandbox.indeed.net/proctor/matrix/definition/$(echo $1 | tr "[:upper:]" "[:lower:]"); unset -f f; }; f'
alias pipetq='f(){ DISPLAY=:0 firefox -new-tab -url https://pipet.sandbox.qa.indeed.net/proctor/matrix/definition/$(echo $1 | tr "[:upper:]" "[:lower:]"); unset -f f; }; f'
alias pp='poodlepants'
alias ppd='poodlepants dev'
alias ppp='poodlepants prod'
alias ppq='poodlepants qa'
alias proc='f(){ DISPLAY=:0 firefox -new-tab -url $PROCTOR_BASE_URL/proctor/definition/$(echo $1 | tr "[:upper:]" "[:lower:]")?branch=${2:-trunk}; unset -f f; }; f'
alias tfs='transpose_first_and_sort'
alias tls='transpose_last_and_sort'
alias trs='transpose_random_and_sort'
alias qalogs='ssh logrepo-rawlogs.qa.indeed.net'
alias umr='update-managed-repos'
alias uph='DISPLAY=:0 firefox -new-tab -url $JETBRAINS_BASE_URL/hub'
alias uraq='GET_THESE_ITEMS="$(cat `find src -name rad-artifacts.json` | \jq .requires[].name | sed "s/\"//g" | sed "s/^/INDEED-qa\//" | tr "\n" " ")" update-rad-artifacts'
