alias ahdhlf='ant hobo-deploy && hobo logs -f $(basename "$PWD")'
alias glogj='glogf --json'
alias og='DISPLAY=:0 firefox -new-tab -url https://code.corp.indeed.com/$(basename $(dirname "$PWD"))/$(basename "$PWD")'
alias ogb='DISPLAY=:0 firefox -new-tab -url https://code.corp.indeed.com/$(basename $(dirname "$PWD"))/$(basename "$PWD")/tree/$(git symbolic-ref --short HEAD)'
alias umr='update-managed-repos'
